### ISSUE TITLE
Proje logosunun belirlenmesi 

### ISSUE THREAD

**Issue by enfyna** [enfyna/seyahat-dostu#18]
Projemizin logosunun yapılması gerekmekte stable diffusion'a güzel bir logo yaptırabilenler burada paylaşırsa iyi bir tanesini seçebiliriz. :)

**Comment by erenaltayy** [comment]
![Seyahat dostu (1)](https://github.com/enfyna/seyahat-dostu/assets/85945886/f79afa68-9a67-48e2-8173-093fae339766)

**Comment by erenaltayy** [comment]
![Seyahat dostu (1)-Photoroom png-Photoroom](https://github.com/enfyna/seyahat-dostu/assets/85945886/40188548-2141-4bb4-b719-f8d2f2eae4f9)
Bu da arkası saydam hali

**Comment by erenaltayy** [comment]
![Adsız tasarım (2)-Photoroom png-Photoroom](https://github.com/enfyna/seyahat-dostu/assets/85945886/c2f1a289-0641-4083-8f3d-898d5f960165)
Bu da navbardaki hali

**Comment by yunusefeyilmaz** [comment]
![Designer](https://github.com/enfyna/seyahat-dostu/assets/89478740/8432447d-e441-4b46-a585-af385b9d3235)

**Comment by erenaltayy** [comment]
![Vintage and Retro Holiday Travel Agent Logo-Photoroom png-Photoroom](https://github.com/enfyna/seyahat-dostu/assets/85945886/a237c49f-0607-4d3e-a3b5-08e3fbe580dd)
Başka bir öneri

**Comment by enfyna** [comment]
![_6fca1258-3d12-49c4-8f0f-33e98e6386b6](https://github.com/enfyna/seyahat-dostu/assets/91965312/2fa36740-bcae-4563-8e5a-8317291dbac6)

Bu da olabilir

**Comment by enfyna** [comment]
Alttaki yazısı silinmiş hali:

![logo](https://github.com/enfyna/seyahat-dostu/assets/91965312/4e3667f8-249d-4926-85d4-94e6f1c33d3b)
