### ISSUE TITLE
Veritabanı Diyagramları

### ISSUE THREAD

**Issue by enfyna** [enfyna/seyahat-dostu#2]
Projemizin veritabanını oluşturabilmemiz için diyagramlarının çizilmesi lazım. Çizilecek diyagramların projemizin hikaye kartlarına ve kullanım klavuzuna uygun olması gerekmekte. Şuan baktığımda Kullanıcı, Seyahat ve Yorum olmak üzere en az 3 tabloya ihtiyacımız var gibi görünüyor.

**Comment by MustafaErkinDal** [comment]
Ben halledeceğim

**Comment by enfyna** [comment]
#6 bu sorunu çözüyor.
