### ISSUE TITLE
Frontend Kurulumu

### ISSUE THREAD

**Issue by enfyna** [enfyna/seyahat-dostu#3]
Projemizde frontend tarafında kullanılmak üzere bir js ve css kütüphanesinin seçilip Sails.js ile uyumlu olacak şekilde kurulması gerekmekte. CSS kütühanesi olarak bence [Tailwind](https://tailwindcss.com/) iyi bir seçim olur.

**Comment by yunusefeyilmaz** [comment]
Tailwind CSS eklendi. #4

**Comment by erenaltayy** [comment]
JS olarak react kullanabiliriz.

**Comment by enfyna** [comment]
#12 ve #10 bu sorunu çözüyor.
